services:
  # postgres:
  #   image: postgres:17.5-alpine
  #   ports:
  #     - ${DATABASE_PORT}:5432
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_DB: ${DATABASE_NAME}
  #   networks:
  #     - cafe_network

  # maildev:
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - ${MAIL_CLIENT_PORT}:1080
  #     - ${MAIL_PORT}:1025
  #   networks:
  #     - cafe_network

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8001:8080
  #   labels:
  #     traefik.enable: "true"
  #     traefik.http.services.adminer.loadbalancer.server.port: ${APP_PORT}
  #     traefik.http.routers.adminer.rule: Host(`adminer.giacaphevietnam.com`)
  #     traefik.http.routers.adminer.tls: "true"
  #   networks:
  #     - traefik_public
  #     - cafe_network

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - cafe_network
networks:
  cafe_network:
    driver: bridge
