-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+mqBWOUJgswRHEAZ
EaALw2wdyeKa4e6R+yRJMjb3EMugCgYIKoZIzj0DAQehRANCAAR3jD05PpYNtUjg
NpXt8ztCusB28rwN2hqq5Isc6dJw2ufhZJUS5FMCkjn1VNgzrlc9eYCa2TiMN+yW
M3atbvwo
-----END PRIVATE KEY-----