export const ON_LOG_OUT = 'ON_LOG_OUT';
const ON_START_PROCESS = 'ON_START_PROCESS';
const ON_END_PROCESS = 'ON_END_PROCESS';
const ON_LOAD_APP = 'ON_LOAD_APP';
const ON_LOAD_APP_END = 'ON_LOAD_APP_END';
const ON_SET_APP_MODE = 'ON_SET_APP_MODE';
const ON_SET_APP_PROFILE = 'ON_SET_APP_PROFILE';
const ON_SET_APP_THEME = 'ON_SET_APP_THEME';
const ON_SET_INTERNET = 'ON_SET_INTERNET';
const ON_SET_TOKEN = 'ON_SET_TOKEN';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_WIFI_DATA = 'SET_WIFI_DATA';
export const SET_LINK_OPEN_APP = 'SET_LINK_OPEN_APP';
export const CHECK_LINK_OPEN_APP = 'CHECK_LINK_OPEN_APP';
const SET_NOTIFICATION_OPEN_APP = 'SET_NOTIFICATION_OPEN_APP';
const ON_RECIVE_NOTIFICATION = 'ON_RECIVE_NOTIFICATION';

export const LIKE_UNLIKE = 'LIKE_UNLIKE';
export const UN_LIKE_LOCAL = 'UN_LIKE_LOCAL';
export const HOME_READY = 'HOME_READY';

export const ON_GET_LIST_ADDRESS = 'ON_GET_LIST_ADDRESS';
export const ON_GET_LIST_ADDRESS_SUCCESS = 'ON_GET_LIST_ADDRESS_SUCCESS';

export const ON_GET_SETTING_APP = 'ON_GET_SETTING_APP';
export const ON_GET_SETTING_APP_SUCCESS = 'ON_GET_SETTING_APP_SUCCESS';

export const ON_CHECK_TOKEN = 'ON_CHECK_TOKEN';
export const ON_CHECK_TOKEN_SUCCESS = 'ON_CHECK_TOKEN_SUCCESS';

export const REFRESHING_PROFILE = 'REFRESHING_PROFILE';
export const REFRESHING_PROFILE_SUCCESS = 'REFRESHING_PROFILE_SUCCESS';
export const SET_DEVICE_TOKEN = 'SET_DEVICE_TOKEN';
export const ON_SET_GEST_ACCOUNT = 'ON_SET_GEST_ACCOUNT';
export const SET_RPODUCT_FOLLOWS = 'SET_RPODUCT_FOLLOWS';

const Constants = {
  SET_DEVICE_TOKEN,
  ON_LOG_OUT,
  ON_START_PROCESS,
  ON_END_PROCESS,
  ON_LOAD_APP,
  ON_LOAD_APP_END,
  ON_SET_APP_MODE,
  ON_SET_APP_PROFILE,
  ON_SET_APP_THEME,
  ON_SET_INTERNET,
  ON_SET_TOKEN,
  SET_LINK_OPEN_APP,
  SET_NOTIFICATION_OPEN_APP,
  ON_RECIVE_NOTIFICATION,
  ON_GET_LIST_ADDRESS,
  ON_GET_LIST_ADDRESS_SUCCESS,
  ON_GET_SETTING_APP,
  ON_GET_SETTING_APP_SUCCESS,
  ON_SET_GEST_ACCOUNT,
  SET_RPODUCT_FOLLOWS,
};
export default Constants;
